collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.3106383
  lightness: 0.6893617
  brandColors:
    - '#B4926E'
    - '#203042'
    - '#FDD665'
    - '#884C4A'
    - '#FFFFF2'
  rhythmicContrast: 0.9042553
typography_spectrum: 0.3042553
layout_spectrum: 0.9340426
name: Clevelandesigns
